### ISSUE TITLE
How to build application?

### ISSUE THREAD

**Issue by Brendonovich** [vinyldarkscratch/lightpad#5]
I've forked and cloned the source code and have all the dependencies in the 'lightpad-master' folder on my laptop, but whenever I run cmake there's always an issue with not finding GooCore/HOWL/Other dependency header files, and if I fix that then the main application header files spit out errors being unable to find their dependencies. Could you make a detailed explanation of where to put the required dependencies and how to run cmake correctly to build the application? I'm working on a similar application to yours as a newbie project but I would like to see what you guys have done so that I can understand how to implement it in my own application. Thanks!

**Comment by queengooborg** [comment]
I'm honored to hear that!  Gosh, this project brings back some memories -- I've kind of dropped it after seeing a general lack of interest.  I just realized that the CMake script doesn't actually load the dependencies from the `submodules/` directory, and for that, I apologize.  An install of all three submodules into `/usr/local/lib` and `/usr/local/include` (assuming you're on macOS/Linux) should do the trick, and running a typical `cmake . && make install` in each folder will default to that install location.

Please be warned: my code is a little more on the spaghetti side of things in this repo, and I've only tested this on macOS!
